FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

COPY TestHachiko/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY TestHachiko /app

RUN chmod +x /app/startup.sh /app/wait-for-it.sh

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["/app/startup.sh"]
