services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - default

  drf:
    build:
      context: .
      dockerfile: Dockerfile-drf
    container_name: bot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./TestHachiko:/app
      - ./TestHachiko/startup.sh:/app/startup.sh
      - ./TestHachiko/wait-for-it.sh:/app/wait-for-it.sh
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: TestHachiko.settings
    entrypoint: ["/bin/bash", "/app/startup.sh"]
    depends_on:
      - db
    networks:
      - default

  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    container_name: bot_app
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: ${API_KEY}
    depends_on:
      - drf
    networks:
      - default

networks:
  default:
    name: bot_network